---
- name: Install FlightStripManager Server
  hosts: all
  remote_user: root
  gather_facts: false

  tasks:
    - name: Install essential software
      ansible.builtin.apt:
        name:
          - python3
          - htop
          - vim
          - screen
        state: present

    - name: Download FSMS executable
      ansible.builtin.get_url:
        url: https://hawk-softworks.de/files/FsmServer-x64-lin-standalone.app
        dest: /opt/FSMS-standalone.app
        mode: '0740'

    - name: Start FSMS
      ansible.builtin.expect:
        command: screen -S fsms-{{ fsms_port }} /opt/FSMS-standalone.app
        responses:
          (?i)custom port?: "y{{ fsms_port }}"
...

